import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";


const inter = Inter({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures text is visible while the font loads
  // If you want to use it with CSS variables (e.g., for Tailwind CSS), add:
  // variable: '--font-inter',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ `${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
